use err_as_you_go::err_as_you_go;

#[err_as_you_go(bar)]
fn foo() {}

fn main() {}
